image: node:12.19.0

stages:
  - dynamic_tests
  - others

npm_scripts:
  stage: others
  variables:
    PROJECT_ROOT: "."
    NPM_SCRIPTS: 'build;ng analytics ci'
    NPM_OUTPUT: "public"
  script:
    - cd $PROJECT_ROOT
    - npm install $NPM_INSTALL_OPTIONS
    - oldIFS=$IFS
    - export IFS=";"
    - for script in $NPM_SCRIPTS; do
    -   IFS=$oldIFS
    -   npm run $script
    -   export IFS=";"
    - done
  artifacts:
    paths:
      - $NPM_OUTPUT

ng_e2e:
    image: node:17-buster
    stage: dynamic_tests
    variables:
      PROJECT_ROOT : '.'
      PROJECT_NAME : ''
      NG_E2E_PACKAGE : ''
      NG_E2E_OPTIONS : ''

    script:
      - npm install
      - ng e2e ${PROJECT_NAME} ${NG_E2E_OPTIONS}

