image: node:12.19.0

stages:
  - build
  - deploy
  - others

cache:
  paths:
    - node_modules/

before_script:
  - npm install

compile:
  stage: build
  script:
    - npm run build
  except:
    - main

npm_scripts:
  stage: others
  script:
    - cd .
    - npm run build
    - mkdir public
    - cp -R dist/ui/* public
  artifacts:
    paths:
      - public

# pages:
#   stage: deploy
#   script:
#     - npm run build
#     - mkdir public
#     - cp -R dist/ui/* public
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
