image: node:12.19.0

stages:
  - dynamic_tests
  - others

# include:
#     - remote: 'https://jobs.r2devops.io/latest/npm_build.yml?scope=0.yml'
#     - remote: 'https://jobs.r2devops.io/pages.yml?scope=0.yml'
#     - remote: 'https://jobs.r2devops.io/latest/npm_install.yml?scope=0.yml'

# npm_build:
#   stage: build
#   variables:
#     NPM_BUILD_OUTPUT_FOLDER: "dist/ui"
#     PAGES_DEPLOY: "true"
# compile:
#   stage: build
#   script:
#     - npm run build
#   except:
#     - main

npm_scripts:
  stage: others
  variables:
    PROJECT_ROOT: "."
    NPM_SCRIPTS: 'build;ng analytics ci'
    NPM_OUTPUT: "public"
  script:
    - cd $PROJECT_ROOT
    - npm install $NPM_INSTALL_OPTIONS
    - oldIFS=$IFS
    - export IFS=";"
    - for script in $NPM_SCRIPTS; do
    -   IFS=$oldIFS
    -   npm run $script
    -   export IFS=";"
    - done
  artifacts:
    paths:
      - $NPM_OUTPUT

ng_e2e:
    image: node:17-buster
    stage: dynamic_tests
    variables:
      PROJECT_ROOT : '.'
      PROJECT_NAME : ''
      NG_E2E_PACKAGE : ''
      NG_E2E_OPTIONS : ''

    script:
      - npm install
      - ng e2e ${PROJECT_NAME} ${NG_E2E_OPTIONS}

# pages:
#   stage: deploy
#   script:
#     - npm run build
#     - mkdir public
#     - cp -R dist/ui/* public

#   artifacts:
#     paths:
#       - public
#   only:
#     - main
