image: node:12.19.0

stages:
  - build
  - deploy
  - others

cache:
  paths:
    - node_modules/

before_script:
  - npm install

compile:
  stage: build
  script:
    - npm run build
  except:
    - main

npm_scripts:
  stage: others
  variables:
    PROJECT_ROOT: "."
    NPM_SCRIPTS: "build;test"
    NPM_OUTPUT: "public"
  script:
    - cd $PROJECT_ROOT
    - for script in ${NPM_SCRIPTS//;/ } ; do
        npm run "+ \"$script\"";
      done
    - mkdir $NPM_OUTPUT
    - cp -R dist/ui/* public
  artifacts:
    paths:
      - $NPM_OUTPUT

# pages:
#   stage: deploy
#   script:
#     - npm run build
#     - mkdir public
#     - cp -R dist/ui/* public
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
