stages:
  - dynamic_tests
variables:
  CYPRESS_CONFIG_FILE : "cypress.json"
  CYPRESS_PROJECT_PATH : "."
  CYPRESS_RECORD_KEY : ""
  CYPRESS_RECORDER : "spec"
  CYPRESS_BASE_URL : ""
  ADDITIONAL_OPTIONS : ""

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  #image: cypress/browsers:node12.14.1-chrome85-ff81
  image: cypress/browsers:node16.5.0-chrome94-ff93
  #image: node:16-buster
  stage: dynamic_tests
  script:
    # install dependencies
    - npm install
    # install module wait-on to ensure that cypress will run after the serve start
    - npm i -g wait-on
    - echo ${Cypress.config('baseUrl')}
    # start the server in the background
    - npm start --no-clipboard & wait-on ${CYPRESS_BASE_URL}
    # run Cypress tests
    #- npx cypress run --browser firefox
    # run Cypress tests
    - if [[ ${CYPRESS_RECORD_KEY} != "" ]]; then
    -   npx cypress run -P ${CYPRESS_PROJECT_PATH} -C ${CYPRESS_CONFIG_FILE} -r ${CYPRESS_RECORDER} ${ADDITIONAL_OPTIONS} --record --parallel
    - else
    -   npx cypress run -P ${CYPRESS_PROJECT_PATH} -C ${CYPRESS_CONFIG_FILE} -r ${CYPRESS_RECORDER} ${ADDITIONAL_OPTIONS}
    - fi
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png


