name: NPM build reusable workflow

on: push
env:
  PROJECT_ROOT: ${{"."}}
  NPM_CI_OPTIONS: ${{""}}
  NPM_BUILD_OPTIONS: ${{""}}
  NPM_TEST_OPTIONS: ${{""}}
jobs:
  npm_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.npm
            ~/.cache/Cypress
          # An explicit key for restoring and saving the cache
          key: ${{runner.os}}-build-${{env.cache-name}}-${{hashFiles('**/package-lock.json')}}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: | # Optional
            ${{runner.os}}-build-${{env.cache-name}}-
      - name: Install dependencies
        run: cd ${{env.PROJECT_ROOT}}
        run: npm ci
  
  npm_build:
    runs-on: ubuntu-latest
    needs: npm_install
    steps:
      - name: Build the project
        run: npm build ${{env.NPM_BUILD_OPTIONS}}

  npm_test:
    runs-on: ubuntu-latest
    needs: npm_install
    steps:
      - name: Test the project
        run: npm test ${{env.NPM_TEST_OPTIONS}}
