name: NPM build reusable workflow

on: push
env:
  PROJECT_ROOT: ${{'.'}}
  NPM_CI_OPTIONS: ${{''}}
  NPM_BUILD_OPTIONS: ${{''}}
  NPM_TEST_OPTIONS: ${{''}}
jobs:
  npm_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: |
            cd ${{env.PROJECT_ROOT}}
            npm ci
  
  npm_build:
    runs-on: ubuntu-latest
    needs: npm_install
    steps:
      - name: Build the project
        run: npm run build ${{env.NPM_BUILD_OPTIONS}}

  npm_test:
    runs-on: ubuntu-latest
    needs: npm_install
    steps:
      - name: Test the project
        run: npm test ${{env.NPM_TEST_OPTIONS}}
